version: "3"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - .:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homework_dev

# open docker shell:
# $ docker ps
#   get the container id
# $ docker exec -it <container id goes here> bash

# to rebuild everything
# $ docker-compose down
# $ docker-compose up -d --force-recreate --build
#
# DATABASE_URL: postgres://user:pass@postgres:5432/db