mutation CreateTransaction(
  $amount: Int!
  $credit: Boolean!
  $debit: Boolean!
  $description: String!
  $merchantId: ID!
  $userId: ID!
) {
  createTransaction(
    amount: $amount
    credit: $credit
    debit: $debit
    description: $description
    merchantId: $merchantId
    userId: $userId
  ) {
    id
    user {
      id
      firstName
      lastName
    }
    merchant {
      id
      name
      description
    }
    description
    debit
    credit
    amount
    insertedAt
  }
}
